### ISSUE TITLE
About comunications between nodes.

### ISSUE THREAD

**Issue by abeneto** [kevoree/kevoree#135]
Hello! I'm sorry because this is not an issue, is only a doubt, but i don't know where i can write the doubts...

I have a system with two nodes, a node in my local machine and the other node in a remote machine. I want that this two nodes can comunicate among them.
1. How can i comunicate the two nodes? There are any component of Kevore allow this? For example, component in node1 sends a text to a component in node2 and it prints the message in a console.

The other question is about "events". I want to allow that one component in a node can throw a Java event (or similar) and another component, in the same node or in other node can be allowed to catch it. Is this possible? There are some component on Kevoree that allow this?

A lot of thanks, one more time.

Alberto.

**Comment by maxleiko** [comment]
You can use the **RemoteWSChan** to make your components communicate. It uses WebSockets to broadcast messages. 
In order for this channel to work, you will have to specify an **host** and a unique id for each channels.

```
// ... your kevscript
add chan: RemoteWSChan/5.2.9-SNAPSHOT
set chan.host = 'ws.kevoree.org'
set chan.uuid = 'your-unique-id'
```

As you can see in the kevscript, you need to specify a remote WebSocket endpoint (ws.kevoree.org). 

If you want to send an "event" to another component (Java or Javascript) you should send a message there is no real "event" concept. But you can make your own by sending specific messages.

**Comment by maxleiko** [comment]
The **RemoteWSChan** is only available in **5.2.9-SNAPSHOT** so you have to explicitly specify the version

**Comment by abeneto** [comment]
First of all a lot of thanks!! I'm trying to do this, but it doesn't work, i supose that i'm doing something wrong. I attach a screenshot with my model. What i'm trying to do? Well, i configure the 2 RemoteWSChannel with the same parameters. Later, I conect the input of one ToyConsole to one of this RemoteWSChannel, ant the output of the other ToyConsole to the other RemoteWSChannel. But the messages that i send isn't received in the other ToyConsole. What's the problem? :(
![kevoreeconection](https://cloud.githubusercontent.com/assets/10678209/7575531/cae4a8de-f835-11e4-9662-340391d5fb90.png)

**Comment by maxleiko** [comment]
If you want to connect an output port to an input port using Kevoree, you should connect the two wires to the same channel.  
Something like this should be better:
![example](http://s17.postimg.org/axos4ua9r/kevoree_chan_example.png)

The KevScript model I used for this:
```
add node0 : JavaNode
add node0.console0, node0.console1 : ToyConsole
add sync : WSGroup
add chan : RemoteWSChan

attach node0 sync

bind node0.console1.showText chan
bind node0.console0.textEntered chan
```

Last week we've fixed some bugs in the Kevoree Standard Library, so now you are not forced to specify the `5.2.9-SNAPSHOT` version as I've released the `5.2.9`

**Comment by maxleiko** [comment]
I've some problem with the public WebSocket endpoint at ws.kevoree.org, I'm trying to fix this.

**Comment by maxleiko** [comment]
Fixed for the endpoint

**Comment by abeneto** [comment]
Perfect!

But, if i want to conect components in 2 nodes that are in different machines? I can't connect this nodes to the same RemoteWSChann... how can do this??

Thanks!!

**Comment by maxleiko** [comment]
You do it the same way. Just be sure to properly set the dictionary attributes to the same host/port/uuid in the RemoteWSChan

**Comment by maxleiko** [comment]
```
add node0, node1 : JavaNode
add node0.console0, node1.console1 : ToyConsole
add sync : WSGroup
add chan : RemoteWSChan
set chan.host = 'ws.kevoree.org'
set chan.uuid = 'something-unique'

attach node0, node1 sync

bind node1.console1.showText chan
bind node0.console0.textEntered chan
```

**Comment by maxleiko** [comment]
You will also need to set which node is the master for the WSGroup so that a WebSocket server is started on this node and the other ones will try to connect to it.

```
set sync.master = "node0"
```

**Comment by abeneto** [comment]
Hello again and sorry for the inconvenience, but it doesn't work :(

I describe you the scenario. I have one standalone Kevoree runtime in my local machine (192.168.1.14)  with this configuration:

add node0 : JavaNode/5.2.9
set node0.log = "INFO"
start node0
add node0.ToyConsol500 : ToyConsole/5.2.9
start node0.ToyConsol500
add RemoteWSC679 : RemoteWSChan/5.2.9
set RemoteWSC679.path = "/"
set RemoteWSC679.port = "80"
set RemoteWSC679.host = "ws.kevoree.org"
set RemoteWSC679.uuid = "myuniqueuuidaabm"
start RemoteWSC679
add sync : WSGroup/5.2.9
start sync
bind node0.ToyConsol500.textEntered RemoteWSC679
attach node0 sync


And i have another Kevoree standalone runtime in a virtualmachine (192.168.1.19) (another ip) with this configuration:

add node0 : JavaNode/5.2.9
add node0.WebEditor203 : WebEditor/5.2.9
add node0.console0 : ToyConsole/5.2.9
add sync : WSGroup/5.2.9
add chan433 : RemoteWSChan/5.2.9

attach node0 sync

bind node0.console0.showText chan433

set chan433.host = 'ws.kevoree.org'
set chan433.uuid = 'myuniqueuuidaabm'
set chan433.path = "/"
set chan433.port = "80"

network node0.ip.1_eth0 192.168.1.19
network node0.ip.0_eth0 fe80:0:0:0:a00:27ff:fed9:fa%eth0

When i try to send a message from 14 to 19, never happens.

What i'm doing wrong?

**Comment by maxleiko** [comment]
You did not use the same channel for your input and your output.

**Comment by abeneto** [comment]
Hello maxleiko!

I'm here one more time. The problem is that, for use the same channel between two models in different machines, i need to do MERGE of the the models.

If i do this, i have a merge in one machine of the two models, and one of this model in the other machine (A+B, and B)

If i do this, the sistem/model B is replicated, and if i have threads in some component in the model B, i have diferent threads in the two machines.

For this, i need to know one kind of comunication between the two machines (two nodes) that no requieres to do merge for connect the two models in the same remotechannel.

I hope that i explained correctly. Sorry for my bad english :)

**Comment by maxleiko** [comment]
Your two nodes have the same name. This cannot work if you want to represent two different machine you have to set different names for them. I think that what you want to represent with a Kevoree model is something like that:

![](http://img11.hostingpics.net/pics/602902abenetoissue.png)
